on:
  push:
    branches:
      - master








jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3  

      - name: "login to docker hub"
        run: docker login --username ${{ secrets.DOCKER_HASNAA }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name : "building docker image"
        run : docker build -t  ${{ secrets.DOCKER_HASNAA }}/myimage .

      - name : "pushing to docker hub"
        run : docker push ${{ secrets.DOCKER_HASNAA }}/myimage